### ISSUE TITLE
Failed to convert page to image'

### ISSUE THREAD

**Issue by GHR-Arash** [mooz/node-pdf-image#30]
```
var pdfImage = new PDFImage('test.pdf');
pdfImage.convertPage(0).then(function (imagePath) {
    console.log(imagePath)
  // 0-th page (first page) of the slide.pdf is available as slide-0.png 
  fs.existsSync(imagePath) // => true 
}).catch(function(error){console.log(error)});
```

{ message: 'Failed to convert page to image',
  error:
   { Error: Command failed: convert 'test.pdf[0]' 'test-0.png'
   Invalid Parameter - 'test-0.png'

       at ChildProcess.exithandler (child_process.js:206:12)
       at emitTwo (events.js:106:13)
       at ChildProcess.emit (events.js:191:7)
       at maybeClose (internal/child_process.js:877:16)
       at Socket.<anonymous> (internal/child_process.js:334:11)
       at emitOne (events.js:96:13)
       at Socket.emit (events.js:188:7)
       at Pipe._handle.close [as _onclose] (net.js:498:12)
     killed: false,
     code: 4,
     signal: null,
     cmd: 'convert \'test.pdf[0]\' \'test-0.png\'' },
  stdout: '',
  stderr: 'Invalid Parameter - \'test-0.png\'\r\n' }

**Comment by augurios** [comment]
+1

**Comment by cesargdm** [comment]
Looks that the problem is with convert, not with node-pdf-image, checkup the path of the file you're giving

**Comment by bruno-serfe** [comment]
same issue here.. what problem with convert? I think we need more information here..

**Comment by dam1** [comment]
Try with another PDF, for me it fail with a PDF v1.3 but works with v1.7

**Comment by MariSelvanDev** [comment]
Same issue .

**Comment by pilapila** [comment]
Same issue.

**Comment by siamraj** [comment]
Same issue is here

**Comment by tiagoernst** [comment]
same issue

**Comment by m5x5** [comment]
Same issue is here.

**Comment by pkantsedalov** [comment]
I've found some workaround of that - look at [this comment please](https://github.com/mooz/node-pdf-image/issues/48#issuecomment-444096550).

**Comment by jaykumarthaker** [comment]
Downgrading GhostScript to 9.23 worked for me..

_though haven't tried on Windows, works on MacOS for sure.._

https://github.com/ArtifexSoftware/ghostpdl-downloads/releases/tag/gs923

**Comment by jaykumarthaker** [comment]
confirmed on Windows as well.. after downgrading GhostScript to 9.23 we have no issue such as _'Invalid Parameter - 'test-0.png'_..
_pdfImage.convertPage(0)_ method works fine, whereas _pdfImage.convertFile()_ doesn't!
